package gt.edu.usac.cats.dominio.conf;


// Generated Jan 27, 2011 10:25:59 PM by Hibernate Tools 3.2.1.GA


import gt.edu.usac.cats.enums.ControlReporte;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

/**
 * Reporte generated by hbm2java
 */
@Entity
@Table(name="reporte"
    ,schema="conf"
)
public class Reporte  implements java.io.Serializable {
    
     private ControlReporte idReporte;
     private String archivoJrxml;
     private String nombre;
     private String nombrePdf;


    public Reporte() {
    }	
    
   
    @Id
    @Column(name="id_reporte", unique=true, nullable=false)
     @Type(
        type = "gt.edu.usac.cats.enums.GenericEnumUserType",
        parameters = {
            @Parameter(
                name = "enumClass",
                value = "gt.edu.usac.cats.enums.ControlReporte"
            ),
            @Parameter(
                name = "identifierMethod",
                value = "toInt"
            ),
            @Parameter(
                name = "valueOfMethod",
                value = "fromInt"
            )
        }
    )
    public ControlReporte getIdReporte() {
        return this.idReporte;
    }
    
    protected void setIdReporte(ControlReporte idReporte) {
        this.idReporte = idReporte;
    }

    
    @Column(name="archivo_jrxml", nullable=false, length=200)
    public String getArchivoJrxml() {
        return this.archivoJrxml;
    }
    
    public void setArchivoJrxml(String archivoJrxml) {
        this.archivoJrxml = archivoJrxml;
    }
    
    @Column(name="nombre", nullable=false, length=65)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="nombre_pdf", length=65)
    public String getNombrePdf() {
        return this.nombrePdf;
    }
    
    public void setNombrePdf(String nombrePdf) {
        this.nombrePdf = nombrePdf;
    }

}


