/*
 * @(#)CursoExtra.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.trabajosocial.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CursoExtra generated by hbm2java
 */
@Entity
@Table(
    name = "curso_extra",
    schema = "control"
)
public class CursoExtra implements java.io.Serializable {
    private short creditos;
    private Estudiante estudiante;
    private short horas;
    private int idCursoExtra;
    private String nombre;
    private boolean tipo;

    public CursoExtra() {}

    public CursoExtra(int idCursoExtra, Estudiante estudiante, String nombre, boolean tipo, short horas,
                      short creditos) {
        this.idCursoExtra = idCursoExtra;
        this.estudiante = estudiante;
        this.nombre = nombre;
        this.tipo = tipo;
        this.horas = horas;
        this.creditos = creditos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_curso_extra",
        unique = true,
        nullable = false
    )
    public int getIdCursoExtra() {
        return this.idCursoExtra;
    }

    public void setIdCursoExtra(int idCursoExtra) {
        this.idCursoExtra = idCursoExtra;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_estudiante",
        nullable = false
    )
    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @Column(
        name = "nombre",
        nullable = false,
        length = 150
    )
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(
        name = "tipo",
        nullable = false
    )
    public boolean isTipo() {
        return this.tipo;
    }

    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }

    @Column(
        name = "horas",
        nullable = false
    )
    public short getHoras() {
        return this.horas;
    }

    public void setHoras(short horas) {
        this.horas = horas;
    }

    @Column(
        name = "creditos",
        nullable = false
    )
    public short getCreditos() {
        return this.creditos;
    }

    public void setCreditos(short creditos) {
        this.creditos = creditos;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
