/*
 * @(#)ProgramaCurso.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.trabajosocial.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgramaCurso generated by hbm2java
 */
@Entity
@Table(
    name = "programa_curso",
    schema = "control"
)
public class ProgramaCurso implements java.io.Serializable {
    private Set<AsignacionIndicador> asignacionIndicadors = new HashSet<AsignacionIndicador>(0);
    private Curso curso;
    private Date fechaAnulacion;
    private Date fechaAprobacion;
    private short idProgramaCurso;

    public ProgramaCurso() {}

    public ProgramaCurso(short idProgramaCurso, Curso curso, Date fechaAprobacion) {
        this.idProgramaCurso = idProgramaCurso;
        this.curso = curso;
        this.fechaAprobacion = fechaAprobacion;
    }

    public ProgramaCurso(short idProgramaCurso, Curso curso, Date fechaAprobacion, Date fechaAnulacion,
                         Set<AsignacionIndicador> asignacionIndicadors) {
        this.idProgramaCurso = idProgramaCurso;
        this.curso = curso;
        this.fechaAprobacion = fechaAprobacion;
        this.fechaAnulacion = fechaAnulacion;
        this.asignacionIndicadors = asignacionIndicadors;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_programa_curso",
        unique = true,
        nullable = false
    )
    public short getIdProgramaCurso() {
        return this.idProgramaCurso;
    }

    public void setIdProgramaCurso(short idProgramaCurso) {
        this.idProgramaCurso = idProgramaCurso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_curso",
        nullable = false
    )
    public Curso getCurso() {
        return this.curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_aprobacion",
        nullable = false,
        length = 13
    )
    public Date getFechaAprobacion() {
        return this.fechaAprobacion;
    }

    public void setFechaAprobacion(Date fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_anulacion",
        length = 13
    )
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }

    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "programaCurso"
    )
    public Set<AsignacionIndicador> getAsignacionIndicadors() {
        return this.asignacionIndicadors;
    }

    public void setAsignacionIndicadors(Set<AsignacionIndicador> asignacionIndicadors) {
        this.asignacionIndicadors = asignacionIndicadors;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
