/*
 * @(#)AsignacionUsuarioPerfil.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AsignacionUsuarioPerfil generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion_usuario_perfil",
    schema = "control",
    uniqueConstraints={
        @UniqueConstraint(name="asignacion_usuario_perfil_uk", columnNames={"id_usuario", "id_perfil"})
    }
)
public class AsignacionUsuarioPerfil implements java.io.Serializable {
    private int idAsignacionUsuarioPerfil;
    private Usuario usuario;
    private Perfil perfil;    

    public AsignacionUsuarioPerfil() {}

    public AsignacionUsuarioPerfil(Usuario usuario, Perfil perfil) {        
        this.usuario = usuario;
        this.perfil = perfil;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion_usuario_perfil",
        unique = true,
        nullable = false
    )
    public int getIdAsignacionUsuarioPerfil() {
        return this.idAsignacionUsuarioPerfil;
    }

    public void setIdAsignacionUsuarioPerfil(int idAsignacionUsuarioPerfil) {
        this.idAsignacionUsuarioPerfil = idAsignacionUsuarioPerfil;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_usuario",
        nullable = false
    )
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_perfil",
        nullable = false
    )
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
