/*
 * @(#)AsignacionEstudianteCarrera.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//~--- JDK imports ------------------------------------------------------------

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AsignacionEstudianteCarrera generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion_estudiante_carrera",
    schema = "control",
    uniqueConstraints={
        @UniqueConstraint(name = "asignacion_estudiante_carrera_semestre_uk",
            columnNames = {"id_estudiante", "id_carrera", "id_semestre"})
    }
)

public class AsignacionEstudianteCarrera implements java.io.Serializable {
    private int idAsignacionEstudianteCarrera;    
    private Date fechaInscripcion;
    private Situacion situacion;
    private Estudiante estudiante;
    private Carrera carrera;    
    private Semestre semestre;



    public AsignacionEstudianteCarrera() {}    

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion_estudiante_carrera",
        unique = true,
        nullable = false
    )
    public int getIdAsignacionEstudianteCarrera() {
        return this.idAsignacionEstudianteCarrera;
    }

    public void setIdAsignacionEstudianteCarrera(int idAsignacionEstudianteCarrera) {
        this.idAsignacionEstudianteCarrera = idAsignacionEstudianteCarrera;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_estudiante",
        nullable = false
    )
    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_carrera",
        nullable = false
    )
    public Carrera getCarrera() {
        return this.carrera;
    }

    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_inscripcion",
        nullable = false,
        length = 13
    )
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }

    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }
    
//______________________________________________________________________________
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_semestre",
        nullable = false
    )
    public Semestre getSemestre() {
        return semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
//______________________________________________________________________________
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_situacion",
        nullable = false
    )
    public Situacion getSituacion() {
        return situacion;
    }

    public void setSituacion(Situacion situacion) {
        this.situacion = situacion;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
