package gt.edu.usac.cats.dominio;

// Generated Jun 21, 2011 5:23:33 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AsignacionEquivalencia generated by hbm2java
 */
@Entity
@Table(name="asignacion_equivalencia"
    ,schema="control"
)
public class AsignacionEquivalencia  implements java.io.Serializable {


     private int idAsignacionEquivalencia;
     private String acuerdoNumero;
     private String observaciones;
     private Set<Asignacion> asignacions = new HashSet<Asignacion>(0);

    public AsignacionEquivalencia() {
    }

	
    public AsignacionEquivalencia(int idAsignacionEquivalencia, String acuerdoNumero) {
        this.idAsignacionEquivalencia = idAsignacionEquivalencia;
        this.acuerdoNumero = acuerdoNumero;
    }
    public AsignacionEquivalencia(int idAsignacionEquivalencia, String acuerdoNumero, String observaciones, Set<Asignacion> asignacions) {
       this.idAsignacionEquivalencia = idAsignacionEquivalencia;
       this.acuerdoNumero = acuerdoNumero;
       this.observaciones = observaciones;
       this.asignacions = asignacions;
    }
   
     @Id 
    
    @Column(name="id_asignacion_equivalencia", unique=true, nullable=false)
    public int getIdAsignacionEquivalencia() {
        return this.idAsignacionEquivalencia;
    }
    
    public void setIdAsignacionEquivalencia(int idAsignacionEquivalencia) {
        this.idAsignacionEquivalencia = idAsignacionEquivalencia;
    }
    
    @Column(name="acuerdo_numero", nullable=false, length=20)
    public String getAcuerdoNumero() {
        return this.acuerdoNumero;
    }
    
    public void setAcuerdoNumero(String acuerdoNumero) {
        this.acuerdoNumero = acuerdoNumero;
    }
    
    @Column(name="observaciones", length=200)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="asignacionEquivalencia")
    public Set<Asignacion> getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set<Asignacion> asignacions) {
        this.asignacions = asignacions;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("AsignacionEquivalencia(idAsignacionEquivalencia = ").
                append(this.idAsignacionEquivalencia).
                append(", acuerdoNumero = \"").append(this.acuerdoNumero).
                append("\")");
        return builder.toString();
    }




}


