/*
 * @(#)AsignacionCursoPensum.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsignacionCursoPensum generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion_curso_pensum",
    schema = "control"
)
public class AsignacionCursoPensum implements java.io.Serializable {
     private short idAsignacionCursoPensum;
     private Curso cursoByIdCursoPrerrequisito;
     private Curso cursoByIdCurso;
     private Pensum pensum;
     private boolean obligatorio;
     private Short creditosPracticos;
     private Short creditosPrerrequisito;
     private Short creditosTeoricos;
     private short numeroSemestre;

    public AsignacionCursoPensum() {}

    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion_curso_pensum",
        unique = true,
        nullable = false
    )
//______________________________________________________________________________
    public short getIdAsignacionCursoPensum() {
        return this.idAsignacionCursoPensum;
    }

    public void setIdAsignacionCursoPensum(short idAsignacionCursoPensum) {
        this.idAsignacionCursoPensum = idAsignacionCursoPensum;
    }
//______________________________________________________________________________
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso", nullable=false)
    public Curso getCursoByIdCurso() {
        return this.cursoByIdCurso;
    }

    public void setCursoByIdCurso(Curso cursoByIdCurso) {
        this.cursoByIdCurso = cursoByIdCurso;
    }
//______________________________________________________________________________
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso_prerrequisito")
    public Curso getCursoByIdCursoPrerrequisito() {
        return this.cursoByIdCursoPrerrequisito;
    }

    public void setCursoByIdCursoPrerrequisito(Curso cursoByIdCursoPrerrequisito) {
        this.cursoByIdCursoPrerrequisito = cursoByIdCursoPrerrequisito;
    }
//______________________________________________________________________________
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_pensum",
        nullable = false
    )
    public Pensum getPensum() {
        return this.pensum;
    }

    public void setPensum(Pensum pensum) {
        this.pensum = pensum;
    }

//______________________________________________________________________________
    @Column(
        name = "obligatorio",
        nullable = false
    )
    public boolean isObligatorio() {
        return this.obligatorio;
    }

    public void setObligatorio(boolean obligatorio) {
        this.obligatorio = obligatorio;
    }
    
//______________________________________________________________________________
    @Column(
        name = "semestre",
        nullable = false
    )

    public short getNumeroSemestre() {
        return this.numeroSemestre;
    }

    public void setNumeroSemestre(short numeroSemestre) {
        this.numeroSemestre = numeroSemestre;
    }

//______________________________________________________________________________
    @Column(name = "creditos_teoricos")
    public Short getCreditosTeoricos() {
        return this.creditosTeoricos;
    }

    public void setCreditosTeoricos(Short creditosTeoricos) {
        this.creditosTeoricos = creditosTeoricos;
    }
//______________________________________________________________________________
    @Column(name = "creditos_practicos")
    public Short getCreditosPracticos() {
        return this.creditosPracticos;
    }

    public void setCreditosPracticos(Short creditosPracticos) {
        this.creditosPracticos = creditosPracticos;
    }
//______________________________________________________________________________
    @Column(name = "creditos_prerrequisito")
    public Short getCreditosPrerrequisito() {
        return this.creditosPrerrequisito;
    }

    public void setCreditosPrerrequisito(Short creditosPrerrequisito) {
        this.creditosPrerrequisito = creditosPrerrequisito;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
