/*
 * @(#)AsignacionCatedraticoHorario.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsignacionCatedraticoHorario generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion_catedratico_horario",
    schema = "control"
)
public class AsignacionCatedraticoHorario implements java.io.Serializable {
    private Catedratico catedratico;
    private Horario horario;
    private int idAsignacionCatedraticoHorario;

    public AsignacionCatedraticoHorario() {
        this.idAsignacionCatedraticoHorario = 0;
    }

    public AsignacionCatedraticoHorario(int idAsignacionCatedraticoHorario, Horario horario, Catedratico catedratico) {
        this.idAsignacionCatedraticoHorario = idAsignacionCatedraticoHorario;
        this.horario = horario;
        this.catedratico = catedratico;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion_catedratico_horario",
        unique = true,
        nullable = false
    )
    public int getIdAsignacionCatedraticoHorario() {
        return this.idAsignacionCatedraticoHorario;
    }

    public void setIdAsignacionCatedraticoHorario(int idAsignacionCatedraticoHorario) {
        this.idAsignacionCatedraticoHorario = idAsignacionCatedraticoHorario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_horario",
        nullable = false
    )
    public Horario getHorario() {
        return this.horario;
    }

    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_catedratico",
        nullable = false
    )
    public Catedratico getCatedratico() {
        return this.catedratico;
    }

    public void setCatedratico(Catedratico catedratico) {
        this.catedratico = catedratico;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
