/*
 * @(#)AsignacionRolPerfil.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsignacionRolPerfil generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion_rol_perfil",
    schema = "control"
)
public class AsignacionRolPerfil implements java.io.Serializable {
    private int idAsignacionRolPerfil;
    private Perfil perfil;
    private Rol rol;

    public AsignacionRolPerfil() {}

    public AsignacionRolPerfil(int idAsignacionRolPerfil, Rol rol, Perfil perfil) {
        this.idAsignacionRolPerfil = idAsignacionRolPerfil;
        this.rol = rol;
        this.perfil = perfil;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion_rol_perfil",
        unique = true,
        nullable = false
    )
    public int getIdAsignacionRolPerfil() {
        return this.idAsignacionRolPerfil;
    }

    public void setIdAsignacionRolPerfil(int idAsignacionRolPerfil) {
        this.idAsignacionRolPerfil = idAsignacionRolPerfil;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_rol",
        nullable = false
    )
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_perfil",
        nullable = false
    )
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
