/*
 * @(#)AsignacionCatedraticoEscuela.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsignacionCatedraticoEscuela generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion_catedratico_escuela",
    schema = "control"
)
public class AsignacionCatedraticoEscuela implements java.io.Serializable {
    private Catedratico catedratico;
    private Escuela escuela;
    private Date fechaFin;
    private Date fechaInicio;
    private Short idAsignacionCatedraticoEscuela;

    public AsignacionCatedraticoEscuela() {
        this.idAsignacionCatedraticoEscuela = 0;
    }

    public AsignacionCatedraticoEscuela(Short idAsignacionCatedraticoEscuela, Escuela escuela, Catedratico catedratico,
            Date fechaInicio) {
        this.idAsignacionCatedraticoEscuela = idAsignacionCatedraticoEscuela;
        this.escuela = escuela;
        this.catedratico = catedratico;
        this.fechaInicio = fechaInicio;
    }

    public AsignacionCatedraticoEscuela(short idAsignacionCatedraticoEscuela, Escuela escuela, Catedratico catedratico,
            Date fechaInicio, Date fechaFin) {
        this.idAsignacionCatedraticoEscuela = idAsignacionCatedraticoEscuela;
        this.escuela = escuela;
        this.catedratico = catedratico;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion_catedratico_escuela",
        unique = true,
        nullable = false
    )
    public short getIdAsignacionCatedraticoEscuela() {
        return this.idAsignacionCatedraticoEscuela;
    }

    public void setIdAsignacionCatedraticoEscuela(short idAsignacionCatedraticoEscuela) {
        this.idAsignacionCatedraticoEscuela = idAsignacionCatedraticoEscuela;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_escuela",
        nullable = false
    )
    public Escuela getEscuela() {
        return this.escuela;
    }

    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_catedratico",
        nullable = false
    )
    public Catedratico getCatedratico() {
        return this.catedratico;
    }

    public void setCatedratico(Catedratico catedratico) {
        this.catedratico = catedratico;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_inicio",
        nullable = false,
        length = 13
    )
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_fin",
        length = 13
    )
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
