/*
 * @(#)Curso.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(
    name = "curso",
    schema = "control"
)
public class Curso implements java.io.Serializable {
    private Set<ProgramaCurso> programaCursos = new HashSet<ProgramaCurso>(0);
    private Set<Prerrequisito> prerrequisitosForIdCursoPrerrequisito = new HashSet<Prerrequisito>(0);
    private Set<Prerrequisito> prerrequisitosForIdCurso = new HashSet<Prerrequisito>(0);
    private Set<Horario> horarios = new HashSet<Horario>(0);
    private Set<Desasignacion> desasignacions = new HashSet<Desasignacion>(0);
    private Set<CursoAprobado> cursoAprobados = new HashSet<CursoAprobado>(0);
    private Set<ConteoAsignacion> conteoAsignacions = new HashSet<ConteoAsignacion>(0);
    private Set<AsignacionCursoPensum> asignacionCursoPensums = new HashSet<AsignacionCursoPensum>(0);
    private String codigo;
    private Short creditosPracticos;
    private Short creditosPrerrequisito;
    private Short creditosTeoricos;
    private short idCurso;
    private String nombre;
    private short semestre;

    public Curso() {}

    public Curso(short idCurso, String codigo, short semestre, String nombre) {
        this.idCurso = idCurso;
        this.codigo = codigo;
        this.semestre = semestre;
        this.nombre = nombre;
    }

    public Curso(short idCurso, String codigo, short semestre, String nombre, Short creditosTeoricos,
                 Short creditosPracticos, Short creditosPrerrequisito, Set<ProgramaCurso> programaCursos,
                 Set<CursoAprobado> cursoAprobados, Set<AsignacionCursoPensum> asignacionCursoPensums,
                 Set<Desasignacion> desasignacions, Set<Horario> horarios,
                 Set<Prerrequisito> prerrequisitosForIdCursoPrerrequisito, Set<ConteoAsignacion> conteoAsignacions,
                 Set<Prerrequisito> prerrequisitosForIdCurso) {
        this.idCurso = idCurso;
        this.codigo = codigo;
        this.semestre = semestre;
        this.nombre = nombre;
        this.creditosTeoricos = creditosTeoricos;
        this.creditosPracticos = creditosPracticos;
        this.creditosPrerrequisito = creditosPrerrequisito;
        this.programaCursos = programaCursos;
        this.cursoAprobados = cursoAprobados;
        this.asignacionCursoPensums = asignacionCursoPensums;
        this.desasignacions = desasignacions;
        this.horarios = horarios;
        this.prerrequisitosForIdCursoPrerrequisito = prerrequisitosForIdCursoPrerrequisito;
        this.conteoAsignacions = conteoAsignacions;
        this.prerrequisitosForIdCurso = prerrequisitosForIdCurso;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_curso",
        unique = true,
        nullable = false
    )
    public short getIdCurso() {
        return this.idCurso;
    }

    public void setIdCurso(short idCurso) {
        this.idCurso = idCurso;
    }

    @Column(
        name = "codigo",
        nullable = false,
        length = 15
    )
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(
        name = "semestre",
        nullable = false
    )
    public short getSemestre() {
        return this.semestre;
    }

    public void setSemestre(short semestre) {
        this.semestre = semestre;
    }

    @Column(
        name = "nombre",
        nullable = false,
        length = 50
    )
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "creditos_teoricos")
    public Short getCreditosTeoricos() {
        return this.creditosTeoricos;
    }

    public void setCreditosTeoricos(Short creditosTeoricos) {
        this.creditosTeoricos = creditosTeoricos;
    }

    @Column(name = "creditos_practicos")
    public Short getCreditosPracticos() {
        return this.creditosPracticos;
    }

    public void setCreditosPracticos(Short creditosPracticos) {
        this.creditosPracticos = creditosPracticos;
    }

    @Column(name = "creditos_prerrequisito")
    public Short getCreditosPrerrequisito() {
        return this.creditosPrerrequisito;
    }

    public void setCreditosPrerrequisito(Short creditosPrerrequisito) {
        this.creditosPrerrequisito = creditosPrerrequisito;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "curso"
    )
    public Set<ProgramaCurso> getProgramaCursos() {
        return this.programaCursos;
    }

    public void setProgramaCursos(Set<ProgramaCurso> programaCursos) {
        this.programaCursos = programaCursos;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "curso"
    )
    public Set<CursoAprobado> getCursoAprobados() {
        return this.cursoAprobados;
    }

    public void setCursoAprobados(Set<CursoAprobado> cursoAprobados) {
        this.cursoAprobados = cursoAprobados;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "curso"
    )
    public Set<AsignacionCursoPensum> getAsignacionCursoPensums() {
        return this.asignacionCursoPensums;
    }

    public void setAsignacionCursoPensums(Set<AsignacionCursoPensum> asignacionCursoPensums) {
        this.asignacionCursoPensums = asignacionCursoPensums;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "curso"
    )
    public Set<Desasignacion> getDesasignacions() {
        return this.desasignacions;
    }

    public void setDesasignacions(Set<Desasignacion> desasignacions) {
        this.desasignacions = desasignacions;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "curso"
    )
    public Set<Horario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "cursoByIdCursoPrerrequisito"
    )
    public Set<Prerrequisito> getPrerrequisitosForIdCursoPrerrequisito() {
        return this.prerrequisitosForIdCursoPrerrequisito;
    }

    public void setPrerrequisitosForIdCursoPrerrequisito(Set<Prerrequisito> prerrequisitosForIdCursoPrerrequisito) {
        this.prerrequisitosForIdCursoPrerrequisito = prerrequisitosForIdCursoPrerrequisito;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "curso"
    )
    public Set<ConteoAsignacion> getConteoAsignacions() {
        return this.conteoAsignacions;
    }

    public void setConteoAsignacions(Set<ConteoAsignacion> conteoAsignacions) {
        this.conteoAsignacions = conteoAsignacions;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "cursoByIdCurso"
    )
    public Set<Prerrequisito> getPrerrequisitosForIdCurso() {
        return this.prerrequisitosForIdCurso;
    }

    public void setPrerrequisitosForIdCurso(Set<Prerrequisito> prerrequisitosForIdCurso) {
        this.prerrequisitosForIdCurso = prerrequisitosForIdCurso;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
