package gt.edu.usac.cats.dominio;
// Generated Feb 24, 2011 5:41:05 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HorarioDia generated by hbm2java
 */
@Entity
@Table(name = "horario_dia", schema = "control")
public class HorarioDia implements java.io.Serializable {

    private int idHorarioDia;
    private Horario horario;
    private int numeroDia;

    public HorarioDia() {
        this.idHorarioDia = 0;
    }

    public HorarioDia(Horario horario, int numeroDia) {
        this.horario = horario;
        this.numeroDia = numeroDia;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_horario_dia", unique = true, nullable = false)
    public int getIdHorarioDia() {
        return this.idHorarioDia;
    }

    public void setIdHorarioDia(int idHorarioDia) {
        this.idHorarioDia = idHorarioDia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_horario", nullable = false)
    public Horario getHorario() {
        return this.horario;
    }

    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    @Column(name = "numero_dia", nullable = false)
    public int getNumeroDia() {
        return this.numeroDia;
    }

    public void setNumeroDia(int numeroDia) {
        this.numeroDia = numeroDia;
    }
}
