/*
 * @(#)Indicador.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Indicador generated by hbm2java
 */
@Entity
@Table(
    name = "indicador",
    schema = "control"
)
public class Indicador implements java.io.Serializable {
    private Set<NotaIndicador> notaIndicadors = new HashSet<NotaIndicador>(0);
    private Set<AsignacionIndicador> asignacionIndicadors = new HashSet<AsignacionIndicador>(0);
    private short codigo;
    private String descripcion;
    private short idIndicador;
    private String nombre;
    private AreaEstudio areaEstudio;

    public Indicador() {}

    public Indicador(short idIndicador, short codigo, String nombre) {
        this.idIndicador = idIndicador;
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Indicador(short idIndicador, short codigo, String nombre, String descripcion,
                     Set<NotaIndicador> notaIndicadors, Set<AsignacionIndicador> asignacionIndicadors) {
        this.idIndicador = idIndicador;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.notaIndicadors = notaIndicadors;
        this.asignacionIndicadors = asignacionIndicadors;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_indicador",
        unique = true,
        nullable = false
    )
    public short getIdIndicador() {
        return this.idIndicador;
    }

    public void setIdIndicador(short idIndicador) {
        this.idIndicador = idIndicador;
    }

    @Column(
        name = "codigo",
        nullable = false
    )
    public short getCodigo() {
        return this.codigo;
    }

    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }

    @Column(
        name = "nombre",
        nullable = false,
        length = 100
    )
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "indicador"
    )
    public Set<NotaIndicador> getNotaIndicadors() {
        return this.notaIndicadors;
    }

    public void setNotaIndicadors(Set<NotaIndicador> notaIndicadors) {
        this.notaIndicadors = notaIndicadors;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "indicador"
    )
    public Set<AsignacionIndicador> getAsignacionIndicadors() {
        return this.asignacionIndicadors;
    }

    public void setAsignacionIndicadors(Set<AsignacionIndicador> asignacionIndicadors) {
        this.asignacionIndicadors = asignacionIndicadors;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_area_estudio",
        nullable = false
    )
    public AreaEstudio getAreaEstudio() {
        return this.areaEstudio;
    }

    public void setAreaEstudio(AreaEstudio areaEstudio) {
        this.areaEstudio = areaEstudio;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
