/*
 * @(#)Pensum.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pensum generated by hbm2java
 */
@Entity
@Table(
    name = "pensum",
    schema = "control"
)
public class Pensum implements java.io.Serializable {
    private Set<AsignacionCursoPensum> asignacionCursoPensums = new HashSet<AsignacionCursoPensum>(0);
    private Carrera carrera;
    private String codigo;
    private Date fechaFin;
    private Date fechaInicio;
    private short idPensum;
    private short estado;

    public Pensum() {}

    public Pensum(short idPensum, Carrera carrera, String codigo, Date fechaInicio) {
        this.idPensum = idPensum;
        this.carrera = carrera;
        this.codigo = codigo;
        this.fechaInicio = fechaInicio;
    }

    public Pensum(short idPensum, short estado, Carrera carrera, String codigo, Date fechaInicio, Date fechaFin,
                  Set<AsignacionCursoPensum> asignacionCursoPensums) {
        this.idPensum = idPensum;
        this.estado = estado;
        this.carrera = carrera;
        this.codigo = codigo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.asignacionCursoPensums = asignacionCursoPensums;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_pensum",
        unique = true,
        nullable = false
    )
    public short getIdPensum() {
        return this.idPensum;
    }

    public void setIdPensum(short idPensum) {
        this.idPensum = idPensum;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(
        name = "id_carrera",
        nullable = false
    )
    public Carrera getCarrera() {
        return this.carrera;
    }

    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    @Column(
        name = "codigo",
        nullable = false,
        length = 20
    )
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_inicio",
        nullable = false,
        length = 13
    )
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(
        name = "fecha_fin",
        length = 13
    )
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "pensum"
    )
    public Set<AsignacionCursoPensum> getAsignacionCursoPensums() {
        return this.asignacionCursoPensums;
    }

    public void setAsignacionCursoPensums(Set<AsignacionCursoPensum> asignacionCursoPensums) {
        this.asignacionCursoPensums = asignacionCursoPensums;
    }

    @Column(name = "estado")
    public short getEstado() {
        return estado;
    }

    public void setEstado(short estado) {
        this.estado = estado;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
