/*
 * @(#)Pensum.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pensum generated by hbm2java
 */
@Entity
@Table(
    name = "pensum",
    schema = "control",
    uniqueConstraints=@UniqueConstraint(columnNames="codigo", name="pensum_codigo_uk")
)
public class Pensum implements java.io.Serializable {
     private short idPensum;
     private Carrera carrera;
     private String codigo;
     private Date fechaInicio;
     private Date fechaFin;
     private Short estado;
     private Set<AsignacionCursoPensum> asignacionCursoPensums = new HashSet<AsignacionCursoPensum>(0);
     private Set<PensumEstudianteCarrera> pensumEstudianteCarreras = new HashSet<PensumEstudianteCarrera>(0);

    public Pensum() {}

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_pensum", unique=true, nullable=false)
    public short getIdPensum() {
        return this.idPensum;
    }

    public void setIdPensum(short idPensum) {
        this.idPensum = idPensum;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_carrera", nullable=false)
    public Carrera getCarrera() {
        return this.carrera;
    }

    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    @Column(name="codigo", nullable=false, length=20, unique=true)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Column(name="estado")
    public Short getEstado() {
        return this.estado;
    }

    public void setEstado(Short estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pensum")
@OrderBy("numeroSemestre")
    public Set<AsignacionCursoPensum> getAsignacionCursoPensums() {
        return this.asignacionCursoPensums;
    }

    public void setAsignacionCursoPensums(Set<AsignacionCursoPensum> asignacionCursoPensums) {
        this.asignacionCursoPensums = asignacionCursoPensums;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pensum")
    public Set<PensumEstudianteCarrera> getPensumEstudianteCarreras() {
        return this.pensumEstudianteCarreras;
    }

    public void setPensumEstudianteCarreras(Set<PensumEstudianteCarrera> pensumEstudianteCarreras) {
        this.pensumEstudianteCarreras = pensumEstudianteCarreras;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Pensum (idPensum=").append(this.idPensum)
                .append(", codigo=").append(this.codigo)
                .append(", estado=").append(this.estado)
                .append(", fechaInicio=").append(this.fechaInicio)
                .append(", fechaFin=").append(this.fechaFin)
                .append(")");
        return builder.toString();
    }


}


//~ Formatted by Jindent --- http://www.jindent.com
