/*
 * @(#)Prerrequisito.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prerrequisito generated by hbm2java
 */
@Entity
@Table(
    name = "prerrequisito",
    schema = "control"
)
public class Prerrequisito implements java.io.Serializable {
    private Curso cursoByIdCurso;
    private Curso cursoByIdCursoPrerrequisito;
    private int idPrerrequisito;

    public Prerrequisito() {}

    public Prerrequisito(int idPrerrequisito, Curso cursoByIdCurso, Curso cursoByIdCursoPrerrequisito) {
        this.idPrerrequisito = idPrerrequisito;
        this.cursoByIdCurso = cursoByIdCurso;
        this.cursoByIdCursoPrerrequisito = cursoByIdCursoPrerrequisito;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_prerrequisito",
        unique = true,
        nullable = false
    )
    public int getIdPrerrequisito() {
        return this.idPrerrequisito;
    }

    public void setIdPrerrequisito(int idPrerrequisito) {
        this.idPrerrequisito = idPrerrequisito;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_curso",
        nullable = false
    )
    public Curso getCursoByIdCurso() {
        return this.cursoByIdCurso;
    }

    public void setCursoByIdCurso(Curso cursoByIdCurso) {
        this.cursoByIdCurso = cursoByIdCurso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_curso_prerrequisito",
        nullable = false
    )
    public Curso getCursoByIdCursoPrerrequisito() {
        return this.cursoByIdCursoPrerrequisito;
    }

    public void setCursoByIdCursoPrerrequisito(Curso cursoByIdCursoPrerrequisito) {
        this.cursoByIdCursoPrerrequisito = cursoByIdCursoPrerrequisito;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
