/*
 * @(#)Usuario.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(
    name = "usuario",
    schema = "control",
    uniqueConstraints={
        @UniqueConstraint(name="usuario_nombre_uk", columnNames={"nombre_usuario"})
    }
)
public class Usuario implements java.io.Serializable {    
    private Set<AsignacionPrimerIngreso> asignacionPrimerIngresos = new HashSet<AsignacionPrimerIngreso>(0);
    private Set<Catedratico> catedraticos = new HashSet<Catedratico>(0);
    private Set<Log> logs = new HashSet<Log>(0);
    private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);
    private Set<AsignacionUsuarioPerfil> asignacionUsuarioPerfils = new HashSet<AsignacionUsuarioPerfil>(0);
    private boolean habilitado;
    private int idUsuario;

    @NotEmpty(message="{validacion.campoObligatorio}")
    private String nombreUsuario;
    @NotEmpty(message="{validacion.campoObligatorio}")
    private String password;
    private String codigoValidacion;


    private Persona persona;

    public Usuario() {}

    public Usuario(int idUsuario, String nombreUsuario, String password, boolean habilitado) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.habilitado = habilitado;
    }

    public Usuario(int idUsuario, String nombreUsuario, String password, boolean habilitado,
                   Set<Catedratico> catedraticos, Set<Log> logs, Set<AsignacionUsuarioPerfil> asignacionUsuarioPerfils,
                   Set<Estudiante> estudiantes) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.habilitado = habilitado;
        this.catedraticos = catedraticos;
        this.logs = logs;
        this.asignacionUsuarioPerfils = asignacionUsuarioPerfils;
        this.estudiantes = estudiantes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_usuario",
        unique = true,
        nullable = false
    )
    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(
        name = "nombre_usuario",
        nullable = false,
        length = 256
    )
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    @Column(
        name = "password",
        nullable = false,
        length = 256
    )
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(
        name = "habilitado",
        nullable = false
    )
    public boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "usuario"
    )
    public Set<Catedratico> getCatedraticos() {
        return this.catedraticos;
    }

    public void setCatedraticos(Set<Catedratico> catedraticos) {
        this.catedraticos = catedraticos;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "usuario"
    )
    public Set<Log> getLogs() {
        return this.logs;
    }

    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "usuario"
    )
    public Set<AsignacionUsuarioPerfil> getAsignacionUsuarioPerfils() {
        return this.asignacionUsuarioPerfils;
    }

    public void setAsignacionUsuarioPerfils(Set<AsignacionUsuarioPerfil> asignacionUsuarioPerfils) {
        this.asignacionUsuarioPerfils = asignacionUsuarioPerfils;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "usuario"
    )
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }

    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }

    @Column(
        name = "codigo_validacion",
        nullable = true,
        length = 256
    )
    public String getCodigoValidacion() {
        return codigoValidacion;
    }

    public void setCodigoValidacion(String codigoValidacion) {
        this.codigoValidacion = codigoValidacion;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        mappedBy = "usuario",
        fetch = FetchType.LAZY
    )
    public Set<AsignacionPrimerIngreso> getAsignacionPrimerIngresos() {
        return this.asignacionPrimerIngresos;
    }

    public void setAsignacionPrimerIngresos(Set<AsignacionPrimerIngreso> asignacionPrimerIngresos) {
        this.asignacionPrimerIngresos = asignacionPrimerIngresos;
    }


    @OneToOne(mappedBy="usuario", cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public Persona getPersona() {
        return persona;
    }

    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    


 }
//~ Formatted by Jindent --- http://www.jindent.com
