/*
 * @(#)Estudiante.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(
    name = "estudiante",
    schema = "control",
    uniqueConstraints={
        @UniqueConstraint(name="estudiante_carne_uk", columnNames={"carne"})
    }
)
public class Estudiante implements java.io.Serializable {
     private int idEstudiante;
     private Nacionalidad nacionalidad;
     private LugarNacimiento lugarNacimiento;
     private Usuario usuario;
     private Pensum pensum;
     private String carne;
     private String nombre;
     private String direccion;
     private String telefono;
     private String celular;
     private String email;
     private Date fechaNacimiento;
     private boolean requisitos;
     private String carneModificado;
     private String nov;
     private char sexo;
     private Set<CuentaCorriente> cuentaCorrientes = new HashSet<CuentaCorriente>(0);
     private Set<Desasignacion> desasignacions = new HashSet<Desasignacion>(0);
     private Set<AsignacionDocumento> asignacionDocumentos = new HashSet<AsignacionDocumento>(0);
     private Set<CursoExtra> cursoExtras = new HashSet<CursoExtra>(0);
     private Set<AsignacionEstudianteCarrera> asignacionEstudianteCarreras = new HashSet<AsignacionEstudianteCarrera>(0);
     private Set<ConteoAsignacion> conteoAsignacions = new HashSet<ConteoAsignacion>(0);

     private String password;
    

    public Estudiante() {}
    
//______________________________________________________________________________
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name="id_estudiante", unique=true, nullable=false)
    public int getIdEstudiante() {
        return this.idEstudiante;
    }

    public void setIdEstudiante(int idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_nacionalidad")
    public Nacionalidad getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(Nacionalidad nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lugar_nacimiento")
    public LugarNacimiento getLugarNacimiento() {
        return this.lugarNacimiento;
    }

    public void setLugarNacimiento(LugarNacimiento lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pensum")
    public Pensum getPensum() {
        return this.pensum;
    }

    public void setPensum(Pensum pensum) {
        this.pensum = pensum;
    }

    @Column(name="carne", unique=true, nullable=false, length=10)
    public String getCarne() {
        return this.carne;
    }

    public void setCarne(String carne) {
        this.carne = carne;
    }

    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="direccion", length=200)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name="telefono", length=10)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name="celular", length=10)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=13)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Column(name="requisitos")
    public boolean isRequisitos() {
        return this.requisitos;
    }

    public void setRequisitos(Boolean requisitos) {
        this.requisitos = requisitos;
    }

    @Column(name="carne_modificado", length=10)
    public String getCarneModificado() {
        return this.carneModificado;
    }

    public void setCarneModificado(String carneModificado) {
        this.carneModificado = carneModificado;
    }

    @Column(name="nov", length=12)
    public String getNov() {
        return this.nov;
    }

    public void setNov(String nov) {
        this.nov = nov;
    }

    @Column(name="sexo", nullable=false, length=1)
    public char getSexo() {
        return this.sexo;
    }

    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<CuentaCorriente> getCuentaCorrientes() {
        return this.cuentaCorrientes;
    }

    public void setCuentaCorrientes(Set<CuentaCorriente> cuentaCorrientes) {
        this.cuentaCorrientes = cuentaCorrientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<Desasignacion> getDesasignacions() {
        return this.desasignacions;
    }

    public void setDesasignacions(Set<Desasignacion> desasignacions) {
        this.desasignacions = desasignacions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<AsignacionDocumento> getAsignacionDocumentos() {
        return this.asignacionDocumentos;
    }

    public void setAsignacionDocumentos(Set<AsignacionDocumento> asignacionDocumentos) {
        this.asignacionDocumentos = asignacionDocumentos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<CursoExtra> getCursoExtras() {
        return this.cursoExtras;
    }

    public void setCursoExtras(Set<CursoExtra> cursoExtras) {
        this.cursoExtras = cursoExtras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<AsignacionEstudianteCarrera> getAsignacionEstudianteCarreras() {
        return this.asignacionEstudianteCarreras;
    }

    public void setAsignacionEstudianteCarreras(Set<AsignacionEstudianteCarrera> asignacionEstudianteCarreras) {
        this.asignacionEstudianteCarreras = asignacionEstudianteCarreras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<ConteoAsignacion> getConteoAsignacions() {
        return this.conteoAsignacions;
    }

    public void setConteoAsignacions(Set<ConteoAsignacion> conteoAsignacions) {
        this.conteoAsignacions = conteoAsignacions;
    }

    @Transient
    public String getPassword() {
        return password;
    }
//______________________________________________________________________________
    public void setPassword(String password) {
        this.password = password;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
