/*
 * @(#)Log.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.cats.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(
    name = "log",
    schema = "control"
)
public class Log implements java.io.Serializable {
    private Date fecha;
    private int idLog;
    private String logger;
    private String mensaje;
    private String prioridad;
    private Usuario usuario;

    public Log() {}

    public Log(int idLog, Usuario usuario, Date fecha) {
        this.idLog = idLog;
        this.usuario = usuario;
        this.fecha = fecha;
    }

    public Log(int idLog, Usuario usuario, Date fecha, String prioridad, String logger, String mensaje) {
        this.idLog = idLog;
        this.usuario = usuario;
        this.fecha = fecha;
        this.prioridad = prioridad;
        this.logger = logger;
        this.mensaje = mensaje;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_log",
        unique = true,
        nullable = false
    )
    public int getIdLog() {
        return this.idLog;
    }

    public void setIdLog(int idLog) {
        this.idLog = idLog;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_usuario",
        nullable = false
    )
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(
        name = "fecha",
        nullable = false,
        length = 29
    )
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(
        name = "prioridad",
        length = 32
    )
    public String getPrioridad() {
        return this.prioridad;
    }

    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }

    @Column(
        name = "logger",
        length = 1024
    )
    public String getLogger() {
        return this.logger;
    }

    public void setLogger(String logger) {
        this.logger = logger;
    }

    @Column(name = "mensaje")
    public String getMensaje() {
        return this.mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
