package gt.edu.usac.cats.dominio;

// Generated Dec 6, 2010 5:32:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Nacionalidad generated by hbm2java
 */
@Entity
@Table(name="nacionalidad"
    ,schema="control"
    , uniqueConstraints = @UniqueConstraint(columnNames="codigo")
)
public class Nacionalidad  implements java.io.Serializable {


     private short idNacionalidad;
     private short codigo;
     private String nombre;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Nacionalidad() {
        this.idNacionalidad = 0;
    }


    public Nacionalidad(short idNacionalidad, short codigo) {
        this.idNacionalidad = idNacionalidad;
        this.codigo = codigo;
    }
    public Nacionalidad(short idNacionalidad, short codigo, String nombre, Set<Estudiante> estudiantes) {
       this.idNacionalidad = idNacionalidad;
       this.codigo = codigo;
       this.nombre = nombre;
       this.estudiantes = estudiantes;
    }

     @Id

    @Column(name="id_nacionalidad", unique=true, nullable=false)
    public short getIdNacionalidad() {
        return this.idNacionalidad;
    }

    public void setIdNacionalidad(short idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }

    @Column(name="codigo", unique=true, nullable=false)
    public short getCodigo() {
        return this.codigo;
    }

    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }

    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="nacionalidad")
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }

    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }

//______________________________________________________________________________
    @Transient
    public String getCodigoNombre(){
        return this.codigo + " - " + (this.nombre == null ? "" : this.nombre);
    }
}


