package gt.edu.usac.cats.dominio;

// Generated Feb 21, 2011 1:17:08 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,schema="control"
    , uniqueConstraints = @UniqueConstraint(columnNames="id_usuario")
)
public class Persona  implements java.io.Serializable {


     private short idPersona;
     private Usuario usuario;
     private String nombre;
     private String registroPersonal;
     private String direccion;
     private String telefono;
     private String celular;
     private String email;
     private char sexo;
     private boolean habilitado;

    public Persona() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_persona", unique=true, nullable=false)
    public short getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(short idPersona) {
        this.idPersona = idPersona;
    }

@OneToOne(fetch=FetchType.LAZY, targetEntity=Usuario.class)
    @JoinColumn(name="id_usuario", unique=true, nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="registro_personal", length=15)
    public String getRegistroPersonal() {
        return this.registroPersonal;
    }

    public void setRegistroPersonal(String registroPersonal) {
        this.registroPersonal = registroPersonal;
    }

    @Column(name="direccion", nullable=false, length=200)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name="telefono", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name="celular", length=10)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Column(name="email", nullable=false, length=60)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name="sexo", nullable=false, length=1)
    public char getSexo() {
        return this.sexo;
    }

    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    @Column(name="habilitado")
    public boolean isHabilitado() {
        return habilitado;
    }

    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }




}


