/*
 * @(#)AreaEstudio.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.trabajosocial.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaEstudio generated by hbm2java
 */
@Entity
@Table(
    name = "area_estudio",
    schema = "control"
)
public class AreaEstudio implements java.io.Serializable {
    private Set<Indicador> indicadores = new HashSet<Indicador>(0);
    private String descripcion;
    private short idAreaEstudio;
    private String nombre;

    public AreaEstudio() {}

    public AreaEstudio(short idAreaEstudio, String nombre) {
        this.idAreaEstudio = idAreaEstudio;
        this.nombre = nombre;
    }

    public AreaEstudio(short idAreaEstudio, String nombre, String descripcion,
                       Set<Indicador> indicadores) {
        this.idAreaEstudio = idAreaEstudio;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.indicadores = indicadores;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_area_estudio",
        unique = true,
        nullable = false
    )
    public short getIdAreaEstudio() {
        return this.idAreaEstudio;
    }

    public void setIdAreaEstudio(short idAreaEstudio) {
        this.idAreaEstudio = idAreaEstudio;
    }

    @Column(
        name = "nombre",
        nullable = false,
        length = 50
    )
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "areaEstudio"
    )
    public Set<Indicador> getIndicadores() {
        return this.indicadores;
    }

    public void setIndicadores(Set<Indicador> indicadores) {
        this.indicadores = indicadores;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
