/*
 * @(#)Asignacion.java   29.03.10
 *
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.trabajosocial.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Asignacion generated by hbm2java
 */
@Entity
@Table(
    name = "asignacion",
    schema = "control"
)
public class Asignacion implements java.io.Serializable {
    private Set<DetalleAsignacion> detalleAsignacions = new HashSet<DetalleAsignacion>(0);
    private Estudiante estudiante;
    private Date fecha;
    private int idAsignacion;
    private TipoAsignacion tipoAsignacion;
    private String transaccion;

    public Asignacion() {}

    public Asignacion(int idAsignacion, Estudiante estudiante, TipoAsignacion tipoAsignacion, String transaccion,
                      Date fecha) {
        this.idAsignacion = idAsignacion;
        this.estudiante = estudiante;
        this.tipoAsignacion = tipoAsignacion;
        this.transaccion = transaccion;
        this.fecha = fecha;
    }

    public Asignacion(int idAsignacion, Estudiante estudiante, TipoAsignacion tipoAsignacion, String transaccion,
                      Date fecha, Set<DetalleAsignacion> detalleAsignacions) {
        this.idAsignacion = idAsignacion;
        this.estudiante = estudiante;
        this.tipoAsignacion = tipoAsignacion;
        this.transaccion = transaccion;
        this.fecha = fecha;
        this.detalleAsignacions = detalleAsignacions;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_asignacion",
        unique = true,
        nullable = false
    )
    public int getIdAsignacion() {
        return this.idAsignacion;
    }

    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_estudiante",
        nullable = false
    )
    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_tipo_asignacion",
        nullable = false
    )
    public TipoAsignacion getTipoAsignacion() {
        return this.tipoAsignacion;
    }

    public void setTipoAsignacion(TipoAsignacion tipoAsignacion) {
        this.tipoAsignacion = tipoAsignacion;
    }

    @Column(
        name = "transaccion",
        nullable = false,
        length = 20
    )
    public String getTransaccion() {
        return this.transaccion;
    }

    public void setTransaccion(String transaccion) {
        this.transaccion = transaccion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(
        name = "fecha",
        nullable = false,
        length = 29
    )
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "asignacion"
    )
    public Set<DetalleAsignacion> getDetalleAsignacions() {
        return this.detalleAsignacions;
    }

    public void setDetalleAsignacions(Set<DetalleAsignacion> detalleAsignacions) {
        this.detalleAsignacions = detalleAsignacions;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
