/*
 * @(#)Rol.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.trabajosocial.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(
    name = "rol",
    schema = "control"
)
public class Rol implements java.io.Serializable {
    private Set<AsignacionRolPerfil> asignacionRolPerfils = new HashSet<AsignacionRolPerfil>(0);
    private String descripcion;
    private short idRol;
    private String nombre;

    public Rol() {}

    public Rol(short idRol, String nombre) {
        this.idRol = idRol;
        this.nombre = nombre;
    }

    public Rol(short idRol, String nombre, String descripcion, Set<AsignacionRolPerfil> asignacionRolPerfils) {
        this.idRol = idRol;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.asignacionRolPerfils = asignacionRolPerfils;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
        name = "id_rol",
        unique = true,
        nullable = false
    )
    public short getIdRol() {
        return this.idRol;
    }

    public void setIdRol(short idRol) {
        this.idRol = idRol;
    }

    @Column(
        name = "nombre",
        nullable = false,
        length = 100
    )
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        mappedBy = "rol"
    )
    public Set<AsignacionRolPerfil> getAsignacionRolPerfils() {
        return this.asignacionRolPerfils;
    }

    public void setAsignacionRolPerfils(Set<AsignacionRolPerfil> asignacionRolPerfils) {
        this.asignacionRolPerfils = asignacionRolPerfils;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
