/*
 * @(#)ConteoAsignacion.java   29.03.10
 * 
 * Universidad de San Carlos de Guatemala
 * Escuela de Trabajo Social
 * Control Academico
 *
 */



package gt.edu.usac.trabajosocial.dominio;

//Generated 16/03/2010 06:31:00 PM by Hibernate Tools 3.2.1.GA

//~--- JDK imports ------------------------------------------------------------

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ConteoAsignacion generated by hbm2java
 */
@Entity
@Table(
    name = "conteo_asignacion",
    schema = "control"
)
public class ConteoAsignacion implements java.io.Serializable {
    private short cantidadAsignaciones;
    private Curso curso;
    private Estudiante estudiante;
    private int idConteoAsignacion;

    public ConteoAsignacion() {}

    public ConteoAsignacion(int idConteoAsignacion, Estudiante estudiante, Curso curso, short cantidadAsignaciones) {
        this.idConteoAsignacion = idConteoAsignacion;
        this.estudiante = estudiante;
        this.curso = curso;
        this.cantidadAsignaciones = cantidadAsignaciones;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(
        name = "id_conteo_asignacion",
        unique = true,
        nullable = false
    )
    public int getIdConteoAsignacion() {
        return this.idConteoAsignacion;
    }

    public void setIdConteoAsignacion(int idConteoAsignacion) {
        this.idConteoAsignacion = idConteoAsignacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_estudiante",
        nullable = false
    )
    public Estudiante getEstudiante() {
        return this.estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id_curso",
        nullable = false
    )
    public Curso getCurso() {
        return this.curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @Column(
        name = "cantidad_asignaciones",
        nullable = false
    )
    public short getCantidadAsignaciones() {
        return this.cantidadAsignaciones;
    }

    public void setCantidadAsignaciones(short cantidadAsignaciones) {
        this.cantidadAsignaciones = cantidadAsignaciones;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
